name: Build & Test

on: push

jobs:

  ###########################################################################
  ## Build Job
  ###########################################################################
  test:
    if: true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - run: echo "Triggered by ${{ github.event_name }} event."
      - name: Check out repository code ${{ github.repository }} on ${{ github.ref }}
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Installing dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install --frozen-lockfile

      - name: Lint
        uses: borales/actions-yarn@v4
        with:
          cmd: lint

      - name: Build
        uses: borales/actions-yarn@v4
        with:
          cmd: build

      - name: Test
        uses: borales/actions-yarn@v4
        with:
          cmd: test
        
      - name: List workspace contents
        run: |
          ls -al